# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by separate terms of service, privacy policy, and support documentation.

name: Build ESAPI Script - v17.0

on:
  workflow_dispatch:
    inputs:
      dateInput:
        description: 'Expiration Date'
        required: true
        default: '1/1/2026'

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_WORKSPACE_PACKAGES_PATH: packages\ESAPI.17.0.0\lib\net48\
      PROJECT_FOLDER_NAME: MAAS-TXIHelper
      PROJECT_NAME: MAAS_TXIHelper
      MAJOR_VERSION: 1
      MINOR_VERSION: 0
      PATCH_VERSION: 0
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Update AssemblyInfo.cs
      id: update_assembly_info
      run: |
        .\.github\workflows\Update-AssemblyInfo.ps1 `
          -AssemblyInfoFilePath .\${{env.PROJECT_FOLDER_NAME}}\Properties\AssemblyInfo.cs `
          -ExpirationDate "${{ github.event.inputs.dateInput }}" `
          -MajorVersion ${{ env.MAJOR_VERSION }} `
          -MinorVersion ${{ env.MINOR_VERSION }} `
          -PatchVersion ${{ env.PATCH_VERSION }} `
          -BuildNumber ${{ env.BUILD_NUMBER }}
          
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: latest
    
    - name: Download nuget packages
      run: nuget install .\MAAS-TXIHelper\packages.config -OutputDirectory .\${{env.PROJECT_FOLDER_NAME}}\packages
   
    - name: Add VIC GitHub NuGet repository
      run: nuget source add
        -Name github `
        -Source "https://nuget.pkg.github.com/Varian-MedicalAffairsAppliedSolutions/index.json" `
        -UserName craman96 `
        -Password ${{ secrets.GITHUB_TOKEN }} `
        -StorePasswordInClearText

    - name: Download nuget package
      run: nuget install ESAPI -Version 17.0.0 -OutputDirectory .\${{env.PROJECT_FOLDER_NAME}}\packages

    - name: Update hint paths in the csproj file
      run: |
        .\.github\workflows\Update-EsapiHintPaths.ps1 `
        -CsprojFilePath .\MAAS-TXIHelper `
        -CsprojFileName MAAS_TXIHelper.csproj
          
    - name: Build Solution
      run: msbuild.exe .\${{env.PROJECT_FOLDER_NAME}}\${{env.PROJECT_NAME}}.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="x64" /p:configuration="Release"
        
    - name: Zip
      run: |
        Compress-Archive `
          -Path ".\${{env.PROJECT_FOLDER_NAME}}\bin\Debug\*" `
          -DestinationPath "${{ github.workspace }}/${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV170.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.9
      with:
        name: ${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV17.0
        tag_name: ${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV17.0
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        body: |
          This is an official release of the **`${{ env.PROJECT_NAME }}`** project.
          Supported Eclipse version: `v17.0`.
          The generated dll is valid until `${{ github.event.inputs.dateInput }}`.
        files: ${{ github.workspace }}/${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV170.zip
